version: '3'

services:
  traefik:
    image: traefik:v2.5

    restart: always

    labels: &traefik-labels
      traefik.enable: "true"
      traefik.http.routers.dashboard.entrypoints: dashboard
      traefik.http.routers.dashboard.rule: "(PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: "777"  # required for swarm mode; any port works here


    environment:  # params defined as env vars rather than CLI params in order to be overridable by stacking docker-compose files
      TRAEFIK_LOG_LEVEL: INFO
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_WATCH: "true"

      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ":80"

      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_ENTRYPOINTS_DASHBOARD_ADDRESS: ":8090"

      TRAEFIK_METRICS_PROMETHEUS: "true"

    ports:
      - "80:80"
      - "8090:8090"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # So that Traefik can listen to the Docker events

    deploy:
      placement:
        constraints:
          - "node.role==manager"
      labels:
        <<: *traefik-labels

  whoami:
    image: "traefik/whoami"
    labels: &whoami-labels
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: "(PathPrefix(`/whoami`))"
      traefik.http.routers.whoami.entrypoints: dashboard
      traefik.http.services.whoami.loadbalancer.server.port: "80"  # required for swarm mode
    deploy:
      labels:
        <<: *whoami-labels
